version: '3'
services:
  nginx-app:
    ports:
      - "3000:80"

  node-app:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=root
      - MONGO_PASSWORD=example
      - SESSION_SECRET=secret
    command: npm run dev
  
  mongoDB-app:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example